# Generated by Django 4.2.8 on 2024-02-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
